name: elk
services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: always
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - node.name=elastic-search
      - cluster.name=elk
      - discovery.type=single-node
      - ELASTIC_PASSWORD=f2170e5030b471551370178f4
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
    mem_limit: 3073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elastic-search:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.16.1
    restart: always
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
      - $STACKS_PATH/elk/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=f2170e5030b471551370178f4
      - SERVER_SSL_ENABLED=false
      - ELASTIC_APM_SECRET_TOKEN=f2170e5030b471551370178f4
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I -s http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  filebeat:
    depends_on:
      elastic-search:
        condition: service_healthy
    image: docker.elastic.co/beats/filebeat:8.16.1
    user: root
    restart: always
    volumes:
      - $STACKS_PATH/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeatdata:/usr/share/filebeat/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    command: filebeat -e -strict.perms=false

volumes:
  esdata: {}
  kibanadata: {}
  filebeatdata: {}
